# Generated by Django 3.0.5 on 2020-05-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestcaseInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='用例名', max_length=160, verbose_name='用例名称')),
                ('module', models.CharField(max_length=80)),
                ('submodule', models.CharField(max_length=80)),
                ('conditions', models.TextField()),
                ('steps', models.TextField()),
                ('expect', models.TextField()),
                ('result', models.BooleanField()),
                ('priority', models.IntegerField()),
                ('ticket', models.CharField(default=None, max_length=20)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
    ]
