# Generated by Django 3.0.5 on 2020-05-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, verbose_name='用例名')),
                ('module', models.CharField(max_length=80, verbose_name='模块名')),
                ('submodule', models.CharField(max_length=80, verbose_name='子模块名')),
                ('conditions', models.TextField(verbose_name='前置条件')),
                ('steps', models.TextField(verbose_name='步骤')),
                ('expect', models.TextField(verbose_name='预期值')),
                ('result', models.BooleanField(verbose_name='测试结果')),
                ('priority', models.IntegerField(verbose_name='优先级')),
                ('ticket', models.CharField(default=None, max_length=20, verbose_name='关联jira')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('extra_data', models.TextField(verbose_name='备注')),
            ],
            options={
                'db_table': 'testcase_tab',
            },
        ),
        migrations.DeleteModel(
            name='TestcaseInfo',
        ),
    ]
