# Generated by Django 3.0.5 on 2020-05-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase_management', '0002_auto_20200505_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='create_time',
            field=models.TimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='update_time',
            field=models.TimeField(verbose_name='更新时间'),
        ),
    ]
