# Generated by Django 3.0.5 on 2020-05-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testcase_management', '0004_auto_20200505_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='result',
        ),
        migrations.AddField(
            model_name='testcase',
            name='author',
            field=models.CharField(default='dan.huo', max_length=32, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='autotest_path',
            field=models.CharField(default='', max_length=128, verbose_name='关联自动化用例路径'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='type',
            field=models.CharField(default='自动', max_length=32, verbose_name='执行方式'),
        ),
        migrations.CreateModel(
            name='Testplan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(default='dan.huo', max_length=32, verbose_name='创建者')),
                ('create_time', models.IntegerField(verbose_name='创建时间')),
                ('extra_data', models.TextField(verbose_name='测试计划描述')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase_management.Testcase')),
            ],
            options={
                'db_table': 'testplan_tab',
            },
        ),
        migrations.CreateModel(
            name='TestcastRunLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.BooleanField(verbose_name='执行结果')),
                ('run_log', models.TextField(verbose_name='执行过程日志')),
                ('run_time', models.IntegerField(verbose_name='执行时间')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase_management.Testcase')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase_management.Testplan')),
            ],
            options={
                'db_table': 'testcase_run_log_tab',
            },
        ),
    ]
