# Generated by Django 3.0.5 on 2020-05-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase_management', '0006_auto_20200505_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcastrunlog',
            old_name='testcase',
            new_name='testcase_id',
        ),
        migrations.RenameField(
            model_name='testcastrunlog',
            old_name='testplan',
            new_name='testplan_id',
        ),
    ]
