# Generated by Django 3.0.5 on 2020-05-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase_management', '0007_auto_20200505_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='id',
            new_name='tid',
        ),
        migrations.RenameField(
            model_name='testplan',
            old_name='id',
            new_name='pid',
        ),
        migrations.RenameField(
            model_name='testplan',
            old_name='case_id',
            new_name='testcase_id',
        ),
    ]
