# Generated by Django 3.0.5 on 2020-05-05 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testcase_management', '0009_auto_20200505_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testplan',
            old_name='extra_data',
            new_name='plan_describe',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='testcase_id',
        ),
        migrations.AddField(
            model_name='testplan',
            name='plan_name',
            field=models.CharField(db_index=True, default='', max_length=128, verbose_name='测试计划名称'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='module',
            field=models.CharField(db_index=True, default='transaction', max_length=80, verbose_name='模块名'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(db_index=True, max_length=160, verbose_name='用例名'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='submodule',
            field=models.CharField(db_index=True, max_length=80, verbose_name='子模块名'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='ticket',
            field=models.CharField(db_index=True, default=None, max_length=20, verbose_name='关联jira'),
        ),
        migrations.CreateModel(
            name='TestPlanMidTab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('testcase_id', models.ForeignKey(db_column='testcase_id', on_delete=django.db.models.deletion.CASCADE, to='testcase_management.Testcase')),
                ('testplan_id', models.ForeignKey(db_column='testplan_id', on_delete=django.db.models.deletion.CASCADE, to='testcase_management.Testplan')),
            ],
            options={
                'db_table': 'testplan_mid_tab',
            },
        ),
    ]
